version: '2'
services:
  webserver:
    # build: Docker/nginx
    image: teste-nginx
    container_name: teste-nginx
    # working_dir: /application
    # volumes:
    #  - ./api:/application
    #  - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:8081"

  php:
    # build: Docker/php-fpm
    image: teste-php
    container_name: teste-php
    # working_dir: /application
    # volumes:
    #   - ./api:/application
    #   - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    ports:
      - "9000:9000"



#    networks:
#      static-network:
#        ipv4_address: 172.20.0.3
# networks:
#   static-network:
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16
#          iprange: 172.28.5.0/24
